version: '3'
services:
  backend:
    build: ./backend-go
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend-svelte
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE=http://backend:8000